; PlatformIO Project Configuration File

; =========================================================
; Node 1 -> Motor Node
; Node 2 -> Tank Node
; Both are NodeMCU (ESP8266)
; =========================================================

[env:motor_node]
platform = espressif8266
board = nodemcuv2
framework = arduino

; ---------- Upload Settings ----------
;upload_port = COM5
;monitor_port = COM5
;monitor_speed = 115200

; ---------- Build Flags ----------
build_flags =
    -D MOTOR_NODE
    -D NODE_NAME=\"MotorNode\"

; ---------- Source File Selection ----------
build_src_filter =
    +<motor_node/>
    +<shared/>

; ---------- Libraries ----------
lib_deps =
    mandulaj/PZEM-004T-v30
    ; Example libraries
    ; knolleary/PubSubClient
    ; bblanchon/ArduinoJson



[env:tank_node]
platform = espressif8266
board = nodemcuv2
framework = arduino

; ---------- Upload Settings ----------
;upload_port = COM6
;monitor_port = COM6
;monitor_speed = 115200

; ---------- Build Flags ----------
build_flags =
    -D TANK_NODE
    -D NODE_NAME=\"TankNode\"

; ---------- Source File Selection ----------
build_src_filter =
    +<tank_node/>
    +<shared/>

; ---------- Libraries ----------
lib_deps =
    ; Example libraries
    ; knolleary/PubSubClient
    ; bblanchon/ArduinoJson